version: 1.0.{build}
build_script:
- cmd: nuget pack Microsoft.VisualStudio.Shared.VsCodeDebugProtocol.Portable.nuspec -Properties version=%APPVEYOR_BUILD_NUMBER%
artifacts:
- path: '**/Microsoft.VisualStudio.Shared.VsCodeDebugProtocol.Portable.*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: hX+xhksIt71D0ynw1SNVba92geWTDEUiPuurX/AZ5Yy7u/TCI3CocSyxHhUlfi/o
  artifact: Microsoft.VisualStudio.Shared.VsCodeDebugProtocol.Portable.*.nupkg